apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=  # base64 encoded "admin"
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=  # base64 encoded "password"
